# Generated by Django 3.1.5 on 2021-03-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadosolicitudlog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estadoprestacionlog',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_logs', to='reintegros.prestacion'),
        ),
        migrations.AddField(
            model_name='estadoprestacionlog',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestacion_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='asignadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_de_auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='auditadoPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='reintegros.etiqueta'),
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='prestacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='reintegros.prestacion'),
        ),
    ]
