# Generated by Django 3.1.5 on 2021-03-22 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0002_auto_20210316_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('enCurso', 'En Curso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='enCurso', max_length=9)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('actualizadoPor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('auditorAsignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='asignadoPor',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='auditadoPor',
        ),
        migrations.RemoveField(
            model_name='prestacion',
            name='estadoActual',
        ),
        migrations.AddField(
            model_name='prestacion',
            name='cobertura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prestacion',
            name='fechaPractica',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prestacion',
            name='periodo',
            field=models.CharField(choices=[('dia', 'Día'), ('mes', 'Mes'), ('trimestre', 'Trimestre'), ('anio', 'Año')], default='mes', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='estadoActual',
            field=models.CharField(choices=[('enCurso', 'En Curso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='enCurso', max_length=9),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='motivoDeRechazo',
            field=models.CharField(choices=[('seleccioneUnaOpcion', 'Seleccione una opcion'), ('faltaDocumentacion', 'Falta Documentación'), ('prestacionNoEstaEnMenuPrestacional', 'Prestación no está en menú prestacional'), ('noTieneAutorizacionPrevia', 'No tiene autorización previa'), ('noCorrespondeCoberturaPorReintegro', 'No corresponde cobertura por reintegro')], default='seleccioneUnaOpcion', max_length=35),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='auditoria',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reintegros.auditoria'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='coseguroNomenclador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='coseguroPrestacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='EstadoPrestacionLog',
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='reintegros.auditoria'),
        ),
    ]
