# Generated by Django 3.1.5 on 2021-03-22 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0003_auto_20210322_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='auditorAsignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditoria_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
