# Generated by Django 3.1.5 on 2021-03-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0005_cuentadeterceros'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='cuentaDeTerceros',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reintegros.cuentadeterceros'),
        ),
        migrations.AddField(
            model_name='archivoadjunto',
            name='cuentaDeTerceros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='reintegros.cuentadeterceros'),
        ),
        migrations.AddField(
            model_name='cuentadeterceros',
            name='autorizacionFinal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuentadeterceros',
            name='responsableDeCarga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_de_terceros', to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='prestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='reintegros.prestacion'),
        ),
    ]
