# Generated by Django 3.1.5 on 2021-03-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0006_auto_20210326_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='cuentaDeTerceros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='reintegros.cuentadeterceros'),
        ),
        migrations.AlterField(
            model_name='archivoadjunto',
            name='prestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos', to='reintegros.prestacion'),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='factura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reintegros.factura'),
        ),
    ]
