# Generated by Django 3.1.5 on 2021-03-29 13:05

from django.db import migrations, models
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0006_auto_20210326_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentadeterceros',
            name='cuitCuil',
            field=models.CharField(max_length=11, validators=[reintegros.validators.cuit_cuil_validator]),
        ),
    ]
