# Generated by Django 3.1.5 on 2021-03-29 13:17

from django.db import migrations, models
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0007_auto_20210329_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentadeterceros',
            name='cbu',
            field=models.CharField(max_length=22, validators=[reintegros.validators.cbu_validator]),
        ),
    ]
