# Generated by Django 3.1.5 on 2021-03-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0008_auto_20210329_1317'),
        ('reintegros', '0007_auto_20210326_2012'),
    ]

    operations = [
    ]
