# Generated by Django 3.1.5 on 2021-03-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0009_merge_20210330_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacion',
            name='coseguroPrestacion',
        ),
    ]
