# Generated by Django 3.1.5 on 2021-03-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0009_merge_20210330_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='auditorActual',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
