# Generated by Django 3.1.5 on 2021-04-08 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0010_remove_prestacion_coseguroprestacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivoadjunto',
            name='etiqueta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='reintegros.etiqueta'),
        ),
    ]
