# Generated by Django 3.1.5 on 2021-04-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0009_merge_20210331_1838'),
        ('reintegros', '0010_auditoria_auditoractual'),
        ('reintegros', '0011_auto_20210408_1734'),
    ]

    operations = [
    ]
