# Generated by Django 3.1.5 on 2021-04-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0012_merge_20210412_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentadeterceros',
            name='delegacion',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_de_terceros', to='reintegros.delegacion'),
            preserve_default=False,
        ),
    ]
