# Generated by Django 3.1.5 on 2021-04-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0013_auto_20210413_1802'),
        ('reintegros', '0013_remove_prestacion_categoria'),
        ('reintegros', '0012_merge_20210413_1932'),
        ('reintegros', '0013_cuentadeterceros_delegacion'),
    ]

    operations = [
    ]
