# Generated by Django 3.1.5 on 2021-04-16 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0014_merge_20210416_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='montoAReintegrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='porcentajeDeCobertura',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
