# Generated by Django 3.1.5 on 2021-04-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0015_auto_20210416_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='montoAReintegrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
