# Generated by Django 3.1.5 on 2021-04-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0014_merge_20210415_2052'),
        ('reintegros', '0017_auto_20210416_1800'),
    ]

    operations = [
    ]
