# Generated by Django 3.1.5 on 2021-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0019_cupon_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='estadoActual',
            field=models.CharField(choices=[('enCurso', 'En Curso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cerrada', 'Cerrada')], default='enCurso', max_length=9),
        ),
    ]
