# Generated by Django 3.1.5 on 2021-04-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0022_cupon_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('enProceso', 'En proceso'), ('pagoRealizado', 'Pago realizado'), ('pagoRechazado', 'Pago rechazado'), ('rechazoParcial', 'Rechazo parcial'), ('cerrado', 'Cerrado')], default='abierto', max_length=14),
        ),
    ]
