# Generated by Django 3.1.5 on 2021-04-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0023_cupon_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='reintegros.lote'),
        ),
    ]
