# Generated by Django 3.1.5 on 2021-04-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0024_auto_20210422_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeCreacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='attachments/archivos_po')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_po', to='reintegros.lote')),
            ],
        ),
    ]
