# Generated by Django 3.1.5 on 2021-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0025_archivopo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivopo',
            name='archivo',
            field=models.FileField(upload_to='archivos_po'),
        ),
    ]
