# Generated by Django 3.1.5 on 2021-04-28 13:19

from django.db import migrations, models
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0026_auto_20210426_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='codigo',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='cbu',
            field=models.CharField(max_length=22, null=True, validators=[reintegros.validators.cbu_validator]),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='cuitCuil',
            field=models.CharField(max_length=11, null=True, validators=[reintegros.validators.cuit_cuil_validator]),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fechaBaja',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='numeroAfiliado',
            field=models.CharField(default='01-01581912/00', max_length=14),
            preserve_default=False,
        ),
    ]
