# Generated by Django 3.1.5 on 2021-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0027_auto_20210428_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
