# Generated by Django 3.1.5 on 2021-04-28 13:23

from django.db import migrations, models
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0028_auto_20210428_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='apellido',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True, validators=[reintegros.validators.cbu_validator]),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='cuitCuil',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[reintegros.validators.cuit_cuil_validator]),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
