# Generated by Django 3.1.5 on 2021-04-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0018_merge_20210426_2024'),
        ('reintegros', '0029_auto_20210428_1323'),
    ]

    operations = [
    ]
