# Generated by Django 3.1.5 on 2021-05-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0030_merge_20210428_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='cuentaDeTerceros',
        ),
    ]
