# Generated by Django 3.1.5 on 2021-05-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0032_cuentadeterceros_afiliado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='cuentaJudicial',
        ),
    ]
