# Generated by Django 3.1.5 on 2021-05-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0035_solicitud_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='lote',
        ),
    ]
