# Generated by Django 3.1.5 on 2021-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0035_solicitud_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='source',
            field=models.CharField(choices=[('interna', 'Interna'), ('vem', 'VEM'), ('bajoPresupuesto', 'Bajo Presupuesto')], default='interna', max_length=15),
        ),
    ]
