# Generated by Django 3.1.5 on 2021-05-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0038_auto_20210521_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tipo',
            field=models.CharField(choices=[('noJudicial', 'No judicial'), ('judicial', 'Judicial')], default='noJudicial', max_length=10),
        ),
    ]
