# Generated by Django 3.1.5 on 2021-05-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0039_lote_tipo'),
        ('reintegros', '0036_solicitud_source'),
    ]

    operations = [
    ]
