# Generated by Django 3.1.5 on 2021-05-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0040_merge_20210526_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='detalleEnvioBanco',
            field=models.FileField(blank=True, null=True, upload_to='informes'),
        ),
    ]
