# Generated by Django 3.1.5 on 2021-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0041_lote_detalleenviobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='totalEnvioBanco',
            field=models.FileField(blank=True, null=True, upload_to='informes'),
        ),
    ]
