# Generated by Django 3.1.5 on 2021-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0042_lote_totalenviobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopo',
            name='fechaDeEjecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivopo',
            name='numeroDeSecuencia',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
