# Generated by Django 3.1.5 on 2021-06-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0042_lote_totalenviobanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='apellido',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='prestador',
            name='areaDes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='domicilio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='especialidadDes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='folio',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestador',
            name='institucionDes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='libro',
            field=models.CharField(default='-', max_length=3),
        ),
        migrations.AddField(
            model_name='prestador',
            name='localidadDes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='lugarNacimiento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='matCondicionMatricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='matFechaExpededTitulo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='matFechaRegistro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='matTipoRegistro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='nacionalidad',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='nombre',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='prestador',
            name='nroDocumento',
            field=models.PositiveIntegerField(default=11111111),
        ),
        migrations.AddField(
            model_name='prestador',
            name='nroMatricula',
            field=models.PositiveSmallIntegerField(default=123),
        ),
        migrations.AddField(
            model_name='prestador',
            name='perEstado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='profEstado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='sexoSisa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='tipoDocumento',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='tituloDes',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='lotecupon',
            name='cupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupon_lote', to='reintegros.cupon'),
        ),
    ]
