# Generated by Django 3.1.5 on 2021-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0043_auto_20210601_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='matricula',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
