# Generated by Django 3.1.5 on 2021-06-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0044_cupon_numerodepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='motivoDeRechazo',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
