# Generated by Django 3.1.5 on 2021-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0046_lote_montototal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='montoTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
