# Generated by Django 3.1.5 on 2021-06-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0048_lote_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoSolicitudLog',
        ),
    ]
