# Generated by Django 3.1.5 on 2021-06-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0050_lote_procesadopor'),
        ('reintegros', '0044_auto_20210601_2020'),
    ]

    operations = [
    ]
