# Generated by Django 3.1.5 on 2021-06-10 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0051_merge_20210604_2051'),
        ('reintegros', '0051_merge_20210604_1920'),
    ]

    operations = [
    ]
