# Generated by Django 3.1.5 on 2021-06-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0052_merge_20210609_1953'),
        ('reintegros', '0052_merge_20210610_1302'),
    ]

    operations = [
    ]
