# Generated by Django 3.1.5 on 2021-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0053_merge_20210610_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nomenclada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='localidadDes',
            field=models.CharField(choices=[('1', 'CABA'), ('2', 'Buenos Aires'), ('3', 'Catamarca'), ('4', 'Chaco'), ('5', 'Chubut'), ('6', 'Córdoba'), ('7', 'Corrientes'), ('8', 'Entre Ríos'), ('9', 'Formosa'), ('10', 'Jujuy'), ('11', 'La Pampa'), ('12', 'La Rioja'), ('13', 'Mendoza'), ('14', 'Misiones'), ('15', 'Neuquén'), ('16', 'Río Negro'), ('17', 'Salta'), ('18', 'San Juan'), ('19', 'San Luis'), ('20', 'Santa Cruz'), ('21', 'Santa Fe'), ('22', 'Santiago del Estero'), ('23', 'Tierra del Fuego'), ('24', 'Tucumán')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nacionalidad',
            field=models.CharField(choices=[('200', 'Argentina'), ('202', 'Bolivia'), ('203', 'Brasil'), ('208', 'Chile'), ('221', 'Paraguay'), ('225', 'Uruguay')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='perEstado',
            field=models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='profEstado',
            field=models.CharField(choices=[('alta', 'Alta'), ('baja', 'Baja')], default='alta', max_length=23),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='sexoSisa',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('A', 'A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'CI'), ('5', 'DE'), ('6', 'DNIF'), ('7', 'DNIM')], max_length=20, null=True),
        ),
    ]
