# Generated by Django 3.1.5 on 2021-06-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0054_auto_20210614_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='cud',
            field=models.IntegerField(null=True),
        ),
    ]
