# Generated by Django 3.1.5 on 2021-06-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0055_afiliado_cud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentadeterceros',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
    ]
