# Generated by Django 3.1.5 on 2021-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0056_cuentadeterceros_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='cud',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
