# Generated by Django 3.1.5 on 2021-06-17 18:34

from django.db import migrations, models
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0057_auto_20210615_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentajudicial',
            name='apellido',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='cuentajudicial',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True, validators=[reintegros.validators.cbu_validator]),
        ),
        migrations.AddField(
            model_name='cuentajudicial',
            name='cuitCuil',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[reintegros.validators.cuit_cuil_validator]),
        ),
        migrations.AddField(
            model_name='cuentajudicial',
            name='nombre',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
