# Generated by Django 3.1.5 on 2021-06-17 19:01

from django.db import migrations, models
import django.db.models.deletion
import reintegros.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0058_auto_20210617_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=70, null=True)),
                ('apellido', models.CharField(blank=True, max_length=70, null=True)),
                ('cuitCuil', models.CharField(blank=True, max_length=11, null=True, validators=[reintegros.validators.cuit_cuil_validator])),
                ('cbu', models.CharField(blank=True, max_length=22, null=True, validators=[reintegros.validators.cbu_validator])),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reintegros.cuentasolicitud'),
        ),
    ]
