# Generated by Django 3.1.5 on 2021-06-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0059_auto_20210617_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentasolicitud',
            name='origen',
            field=models.CharField(choices=[('cuentaAfiliado', 'Cuenta afiliado'), ('cuentaDeTerceros', 'Cuenta de terceros'), ('cuentaJudicial', 'Cuenta judicial')], default='cuentaAfiliado', max_length=16),
        ),
    ]
