# Generated by Django 3.1.5 on 2021-06-28 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reintegros', '0060_cuentasolicitud_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='auditorActual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='estadoActual',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado')], default='rechazado', max_length=9),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='motivoDeRechazo',
            field=models.CharField(blank=True, choices=[('seleccioneUnaOpcion', 'Seleccione una opcion'), ('faltaDocumentacion', 'Falta Documentación'), ('prestacionNoEstaEnMenuPrestacional', 'Prestación no está en menú prestacional'), ('noTieneAutorizacionPrevia', 'No tiene autorización previa'), ('noCorrespondeCoberturaPorReintegro', 'No corresponde cobertura por reintegro')], default='seleccioneUnaOpcion', max_length=35, null=True),
        ),
    ]
