# Generated by Django 3.1.5 on 2021-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0061_auto_20210628_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentajudicial',
            name='estado',
            field=models.CharField(choices=[('inactiva', 'Inactiva'), ('activa', 'Activa')], default='activa', max_length=9),
        ),
        migrations.AlterField(
            model_name='cuentadeterceros',
            name='estado',
            field=models.CharField(choices=[('inactiva', 'Inactiva'), ('pendiente', 'Pendiente'), ('aprobada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=9),
        ),
    ]
