# Generated by Django 3.1.5 on 2021-06-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0062_auto_20210629_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentajudicial',
            name='oficioJudicial',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
