# Generated by Django 3.1.5 on 2021-08-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0063_auto_20210629_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestacion',
            name='factura',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='factura',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reintegros.factura'),
        ),
    ]
