# Generated by Django 3.1.5 on 2021-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0063_auto_20210629_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='estadoActual',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado'), ('desvinculado', 'Desvinculado de lote')], default='rechazado', max_length=12),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('enProceso', 'En proceso'), ('pagoRealizado', 'Pago realizado'), ('pagoRechazado', 'Pago rechazado'), ('rechazoParcial', 'Rechazo parcial'), ('cerrado', 'Cerrado'), ('desvinculado', 'Desvinculado de lote')], default='abierto', max_length=14),
        ),
        migrations.AlterField(
            model_name='lotecupon',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('enProceso', 'En proceso'), ('pagoRealizado', 'Pago realizado'), ('pagoRechazado', 'Pago rechazado'), ('rechazoParcial', 'Rechazo parcial'), ('cerrado', 'Cerrado'), ('desvinculado', 'Desvinculado de lote')], default='abierto', max_length=14),
        ),
    ]
