# Generated by Django 3.1.5 on 2021-08-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0064_auto_20210802_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacion',
            name='fechaPracticaHasta',
            field=models.DateField(null=True),
        ),
    ]
