# Generated by Django 3.1.5 on 2021-08-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0013_remove_nomenclador_categoria'),
        ('reintegros', '0065_prestacion_fechapracticahasta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
