# Generated by Django 3.1.5 on 2021-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0066_delete_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='valorIprossNomenclador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='valorPrestacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
