# Generated by Django 3.1.5 on 2021-08-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0067_auto_20210810_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='montoAReintegrar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
