# Generated by Django 3.1.5 on 2021-08-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0065_auto_20210723_2023'),
        ('reintegros', '0069_auto_20210811_1528'),
    ]

    operations = [
    ]
