# Generated by Django 3.1.5 on 2021-08-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0070_merge_20210819_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacion',
            name='fechaPracticaHasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
