# Generated by Django 3.1.5 on 2021-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0071_auto_20210820_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='discapacitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('noProcesado', 'No procesado'), ('procesadoOk', 'Procesado ok'), ('procesadoConError', 'Procesado con error'), ('eliminado', 'Eliminado')], default='noProcesado', max_length=17),
        ),
    ]
