# Generated by Django 3.1.5 on 2021-10-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0073_auto_20211006_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='especialidadDes',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestador',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'CI'), ('5', 'DE'), ('6', 'DNIF'), ('7', 'DNIM')], default=1, max_length=20),
        ),
    ]
