# Generated by Django 3.1.5 on 2021-10-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('reintegros', '0073_merge_20210821_0057'),
        ('reintegros', '0073_auto_20211006_2309'),
    ]

    operations = [
    ]
