# Generated by Django 3.1.5 on 2021-10-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0074_merge_20211006_2309'),
        ('reintegros', '0074_auto_20211020_1947'),
    ]

    operations = [
    ]
