# Generated by Django 3.1.5 on 2021-11-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0074_auto_20211020_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='especialidadDes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='localidadDes',
            field=models.CharField(choices=[('1', 'CABA'), ('2', 'Buenos Aires'), ('3', 'Catamarca'), ('4', 'Chaco'), ('5', 'Chubut'), ('6', 'Córdoba'), ('7', 'Corrientes'), ('8', 'Entre Ríos'), ('9', 'Formosa'), ('10', 'Jujuy'), ('11', 'La Pampa'), ('12', 'La Rioja'), ('13', 'Mendoza'), ('14', 'Misiones'), ('15', 'Neuquén'), ('16', 'Río Negro'), ('17', 'Salta'), ('18', 'San Juan'), ('19', 'San Luis'), ('20', 'Santa Cruz'), ('21', 'Santa Fe'), ('22', 'Santiago del Estero'), ('23', 'Tierra del Fuego'), ('24', 'Tucumán')], default='Río Negro', max_length=100),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nroDocumento',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='tipoDocumento',
            field=models.CharField(choices=[('1', 'DNI'), ('2', 'LC'), ('3', 'LE'), ('4', 'CI'), ('5', 'DE'), ('6', 'DNIF'), ('7', 'DNIM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='tituloDes',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
