# Generated by Django 3.1.5 on 2021-11-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0075_auto_20211102_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='nroDocumento',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
