# Generated by Django 3.1.5 on 2021-11-15 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0076_auto_20211102_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
