# Generated by Django 3.1.5 on 2021-11-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0076_auto_20211102_1441'),
        ('reintegros', '0075_merge_20211021_1754'),
    ]

    operations = [
    ]
