# Generated by Django 3.1.5 on 2021-11-15 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0079_auto_20211115_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
