# Generated by Django 3.1.5 on 2021-11-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0077_merge_20211102_1518'),
        ('reintegros', '0081_auto_20211115_2021'),
    ]

    operations = [
    ]
