# Generated by Django 3.1.5 on 2021-11-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0081_auto_20211115_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='lastUpdate',
        ),
    ]
