# Generated by Django 3.1.5 on 2021-12-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0082_merge_20211119_1256'),
        ('reintegros', '0082_remove_afiliado_lastupdate'),
    ]

    operations = [
    ]
