# Generated by Django 3.1.5 on 2021-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomenclador",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modalidadPresentacion",
                    models.CharField(
                        choices=[
                            ("ambulatoria", "Ambulatoria"),
                            ("internacion", "Internación"),
                        ],
                        default="ambulatoria",
                        max_length=12,
                    ),
                ),
                ("capitulo", models.DecimalField(decimal_places=0, max_digits=2)),
                ("areaCubrir", models.DecimalField(decimal_places=0, max_digits=8)),
                ("codigo", models.DecimalField(decimal_places=0, max_digits=10)),
                ("descripcion", models.CharField(max_length=100)),
                (
                    "complejidadPractica",
                    models.DecimalField(decimal_places=0, max_digits=1),
                ),
                ("unidadGalenoAyudante", models.IntegerField()),
                ("unidadGalenoEspecialista", models.IntegerField()),
                ("unidadGasto", models.IntegerField()),
                ("unidadMateriales", models.IntegerField()),
                ("valorAyudante", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "valorEspecialista",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("valorGasto", models.DecimalField(decimal_places=2, max_digits=6)),
                ("valorMontoFijo", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "montoFijoMensual",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("valorIpross", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "catPresPracticaLugar",
                    models.DecimalField(decimal_places=0, max_digits=1),
                ),
                (
                    "catPresPracticaEspecialista",
                    models.DecimalField(decimal_places=0, max_digits=1),
                ),
                ("programaSanitario", models.CharField(max_length=100)),
                ("topesCoberturaPeriodo", models.IntegerField()),
                (
                    "periodoTope",
                    models.CharField(
                        choices=[
                            ("dia", "Día"),
                            ("mes", "Mes"),
                            ("trimestre", "Trimestre"),
                            ("anio", "Año"),
                        ],
                        default="mes",
                        max_length=10,
                    ),
                ),
                ("numeroNormaRespaldatoria", models.CharField(max_length=6)),
                ("fechaNorma", models.DateField()),
            ],
        ),
    ]
