# Generated by Django 3.1.5 on 2021-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclador',
            name='catPresPracticaEspecialista',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='catPresPracticaLugar',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='montoFijoMensual',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='unidadGalenoAyudante',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='unidadGalenoEspecialista',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='unidadGasto',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='unidadMateriales',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='valorAyudante',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='valorEspecialista',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='valorGasto',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='valorMontoFijo',
        ),
        migrations.AlterField(
            model_name='nomenclador',
            name='complejidadPractica',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
