# Generated by Django 3.1.5 on 2021-03-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0002_auto_20210305_1444'),
        ('nomenclador', '0002_capitulo'),
    ]

    operations = [
    ]
