# Generated by Django 3.1.5 on 2021-03-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0003_merge_20210305_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomenclador.capitulo'),
        ),
    ]
