# Generated by Django 3.1.5 on 2021-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0004_auto_20210305_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='valorIpross',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
