# Generated by Django 3.1.5 on 2021-03-31 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0005_auto_20210310_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclador',
            name='areaCubrir',
        ),
        migrations.RemoveField(
            model_name='nomenclador',
            name='programaSanitario',
        ),
    ]
