# Generated by Django 3.1.5 on 2021-04-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reintegros', '0013_remove_prestacion_categoria'),
        ('nomenclador', '0006_auto_20210331_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclador',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='reintegros.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomenclador',
            name='requiereAuditoriaMedica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nomenclador',
            name='unidad',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomenclador',
            name='codigo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
