# Generated by Django 3.1.5 on 2021-04-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0007_auto_20210414_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='unidad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
