# Generated by Django 3.1.5 on 2021-04-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0008_auto_20210414_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomenclador',
            old_name='modalidadPresentacion',
            new_name='modalidadPrestacion',
        ),
    ]
