# Generated by Django 3.1.5 on 2021-06-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0010_auto_20210426_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='unidad',
            field=models.CharField(blank=True, choices=[('km', 'km'), ('hs', 'hs'), ('sesiones', 'Sesiones'), ('unidades', 'Unidades')], default='unidades', max_length=8, null=True),
        ),
    ]
