# Generated by Django 3.1.5 on 2021-08-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0012_nomenclador_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclador',
            name='categoria',
        ),
    ]
