# Generated by Django 3.1.5 on 2021-08-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0013_remove_nomenclador_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclador',
            name='fechaNormaHasta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nomenclador',
            name='modalidadPrestacion',
            field=models.CharField(choices=[('ambulatorio', 'Ambulatorio'), ('internacion', 'Internación'), ('internacionyambulatoria', 'Internación y Ambulatoria')], default='ambulatoria', max_length=23),
        ),
        migrations.AlterField(
            model_name='nomenclador',
            name='periodoTope',
            field=models.CharField(blank=True, choices=[('dia', 'Día'), ('mes', 'Mes'), ('trimestre', 'Trimestre'), ('anio', 'Año')], default='mes', max_length=10, null=True),
        ),
    ]
