# Generated by Django 3.1.5 on 2021-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0014_auto_20210809_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
