# Generated by Django 3.1.5 on 2021-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0017_auto_20210809_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='valorIpross',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
