# Generated by Django 3.1.5 on 2021-08-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0018_auto_20210809_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='descripcion',
            field=models.CharField(max_length=120),
        ),
    ]
