# Generated by Django 3.1.5 on 2021-09-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0021_auto_20210819_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='periodoTope',
            field=models.CharField(blank=True, choices=[('porunicavez', 'Día'), ('mensual', 'Mes'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('catrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mes', max_length=13, null=True),
        ),
    ]
