# Generated by Django 3.1.5 on 2021-10-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0022_auto_20210913_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='periodoTope',
            field=models.CharField(blank=True, choices=[('porunicavez', 'Día'), ('mensual', 'Mes'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('catrimestral', 'Cuatrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=40, null=True),
        ),
    ]
