# Generated by Django 3.1.5 on 2021-11-15 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0023_auto_20211006_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclador',
            name='lastUpdate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='nomenclador',
            name='modalidadPrestacion',
            field=models.CharField(choices=[('ambulatorio', 'Ambulatorio'), ('internacion', 'Internación')], default='ambulatoria', max_length=23),
        ),
    ]
