# Generated by Django 3.1.5 on 2021-11-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0028_auto_20211115_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomenclador',
            old_name='fechaNorma',
            new_name='fechaVigencia',
        ),
        migrations.RenameField(
            model_name='nomenclador',
            old_name='fechaNormaHasta',
            new_name='fechaVigenciaHasta',
        ),
    ]
