# Generated by Django 3.1.5 on 2021-11-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0029_auto_20211129_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclador',
            name='modalidadPrestacion',
            field=models.CharField(choices=[('ambulatorio', 'Ambulatorio'), ('internación', 'Internación')], default='ambulatoria', max_length=23),
        ),
    ]
