# Generated by Django 3.1.5 on 2021-12-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0030_auto_20211129_2117'),
        ('nomenclador', '0030_auto_20211201_1739'),
    ]

    operations = [
    ]
