# Generated by Django 3.1.5 on 2021-03-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='delegacionPreferida',
            new_name='delegacionPrincipal',
        ),
    ]
