# Generated by Django 3.1.5 on 2021-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenclador', '0009_auto_20210415_1843'),
        ('usuario', '0002_auto_20210318_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='capitulos',
            field=models.ManyToManyField(blank=True, to='nomenclador.Capitulo'),
        ),
    ]
