# Generated by Django 3.1.5 on 2021-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_capitulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='casaCentral',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
