# Generated by Django 3.1.5 on 2021-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_casacentral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='casaCentral',
            field=models.BooleanField(default=False),
        ),
    ]
