# Generated by Django 3.1.5 on 2021-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud', 'Solicitud'), ('autorizacion', 'Autorizacion')], default='solicitud', max_length=12),
        ),
    ]
