# Generated by Django 3.1.5 on 2021-11-29 21:17

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='lastUpdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
